export const WHITE_COLOR = '#ffffff'
export const BUTTONS_CONTAINER_COLOR = '#79bbef'
export const TIMER_CONTAINER_COLOR = '#fd6e6a'
export const BUTTON_COLOR = '#2196f3'
export const BUTTON_ENABLED_COLOR = 'red'
export const BUTTON_DISABLED_COLOR = '#cccccc'
export const BG_GRADIENT_COLOR = ['#97ABFF', '#3b5998', '#123597']
export const CIRCULAR_TINT_COLOR = '#2196f3'
export const CIRCULAR_BG_COLOR = '#79bbef'
