export const HALF_UNIT = '4px'
export const SINGLE_UNIT = '8px'
export const DOUBLE_UNIT = '16px'
export const TRIPLE_UNIT = '20px'
export const QUADRIPLE_UNIT = '32px'
export const EIGHT_UNIT = '64px'
